export const REQUEST_TRENDING = 'REQUEST_TRENDING'
export const RECEIVE_TRENDING = 'RECEIVE_TRENDING'

export const REQUEST_SEARCH = 'REQUEST_SEARCH'
export const RECEIVE_SEARCH = 'RECEIVE_SEARCH'

export const UPLOADING_GIF = 'UPLOADING_GIF'
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS'
export const UPLOAD_FAILED = 'UPLOAD_FAILED'
export const UPLOAD_RESET = 'UPLOAD_RESET'
